### ISSUE TITLE
Configurar middleware de CORS

### ISSUE THREAD

**Issue by ETE12** [robertrooch/CPM-Back-Equipo03#2]
**Tareas**
- [ ] Instalar el paquete cors.
- [ ] Configurar CORS en server.js para permitir solicitudes desde http://localhost:4200.
- [ ] Probar que las solicitudes desde el frontend son aceptadas sin errores de CORS.

**Comment by robertrooch** [comment]
Closes #2

- [x] Instalar el paquete cors.
- [x] Configurar CORS en server.js para permitir solicitudes desde http://localhost:4200/.
- [x] Probar que las solicitudes desde el frontend son aceptadas sin errores de CORS.
